application: telemarkalpint
version: 62
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- static/.*
- build/.*

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static
#- url: /media/admin
#  static_dir: django/contrib/admin/media
#  expiration: '0'

- url: /tasks/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
  secure: optional

error_handlers:
    - error_code: timeout
      file: templates/timeout.html

    - error_code: over_quota
      file: templates/over_quota.html

libraries:
- name: pycrypto
  version: "2.6"