application: telemarkalpint
version: 69
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- slingsby/static/.*
- slingsby/static-src/.*
- node_modules/.*
- Gruntfile.js
- package.json
- \..*

handlers:
- url: /static
  static_dir: slingsby/static
#- url: /media/admin
#  static_dir: django/contrib/admin/media
#  expiration: '0'

- url: /tasks/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
  secure: optional

error_handlers:
    - error_code: timeout
      file: slingsby/templates/timeout.html

    - error_code: over_quota
      file: slingsby/templates/over_quota.html

libraries:
- name: pycrypto
  version: "2.6"
